name:                ybt
version:             0.1.0.0
github:              "githubuser/ybt"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ybt#readme>

dependencies:
- base >= 4.7 && < 5
- monad-loops >=0.4.3
#- cryptohash >=0.11.9
- bytestring >= 0.10.8.2
- cryptohash-sha512 >= 0.11.100.1
- HTTP >= 4000.3.9
- time >= 1.8.0.2
- wreq >= 0.5.2.0
- lens >= 4.15.4
- aeson >= 1.2.3.0
- utf8-string >=1.0.1.1
#- network-uri-json >= 0.1.2.1
- hex >= 0.1.2
- text >= 1.2.3.0

library:
  source-dirs: src

executables:
  ybt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ybt

tests:
  ybt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ybt
